version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=diego
      - POSTGRES_DB=test
  spring-boot-docker-demo:
    build: .
    #container_name: spring-boot-docker-demo #To sacale a service no name has to be specified
    expose:
      - 8080
    ports:
      - "8081-8090:8080"
    depends_on:
      - postgres

volumes:
    postgres-data: