server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: diego
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

jwt:
  secret: javainuse

demo:
  api:
    context-path: /api/v1/persons
    endpoints:
      save: ${demo.api.context-path}/
      get-by-id: ${demo.api.context-path}/{id}
      list: ${demo.api.context-path}/
      update-put: ${demo.api.context-path}/{id}
      delete: ${demo.api.context-path}/{id}
      upload: ${demo.api.context-path}/upload-csv