server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: diego
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

jwt:
  secret: javainuse